//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoinbaseAdvancedTradeClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoinbaseAdvancedTradeClient.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Account ID is required..
        /// </summary>
        public static string AccountIdRequired {
            get {
                return ResourceManager.GetString("AccountIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The amount must be greater than zero..
        /// </summary>
        public static string AmountParameterRange {
            get {
                return ResourceManager.GetString("AmountParameterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An API Configuration is required..
        /// </summary>
        public static string ApiConfigRequired {
            get {
                return ResourceManager.GetString("ApiConfigRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An API Key is required..
        /// </summary>
        public static string ApiKeyRequired {
            get {
                return ResourceManager.GetString("ApiKeyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An API Secret is required..
        /// </summary>
        public static string ApiSecretRequired {
            get {
                return ResourceManager.GetString("ApiSecretRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid candle granularity..
        /// </summary>
        public static string CandleGranularityInvalid {
            get {
                return ResourceManager.GetString("CandleGranularityInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A valid channel is required..
        /// </summary>
        public static string ChannelRequired {
            get {
                return ResourceManager.GetString("ChannelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An end date is required..
        /// </summary>
        public static string EndDateRequired {
            get {
                return ResourceManager.GetString("EndDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;limit&apos; parameter must be between 1 and 250..
        /// </summary>
        public static string LimitParameterRange {
            get {
                return ResourceManager.GetString("LimitParameterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The limit price must be greater than zero..
        /// </summary>
        public static string LimitPriceParameterRange {
            get {
                return ResourceManager.GetString("LimitPriceParameterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A message received callback is required. This is a method that will be invoked when a WebSocket message is received..
        /// </summary>
        public static string MessageReceivedCallbackRequired {
            get {
                return ResourceManager.GetString("MessageReceivedCallbackRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;offset&apos; parameter must be greater than zero..
        /// </summary>
        public static string OffsetParameterRange {
            get {
                return ResourceManager.GetString("OffsetParameterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order configuration..
        /// </summary>
        public static string OrderConfigurationInvalid {
            get {
                return ResourceManager.GetString("OrderConfigurationInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Order ID is required..
        /// </summary>
        public static string OrderIdRequired {
            get {
                return ResourceManager.GetString("OrderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An order is required..
        /// </summary>
        public static string OrderParametersRequired {
            get {
                return ResourceManager.GetString("OrderParametersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order placement source..
        /// </summary>
        public static string OrderPlacementSourceInvalid {
            get {
                return ResourceManager.GetString("OrderPlacementSourceInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order side..
        /// </summary>
        public static string OrderSideInvalid {
            get {
                return ResourceManager.GetString("OrderSideInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid order type..
        /// </summary>
        public static string OrderTypeInvalid {
            get {
                return ResourceManager.GetString("OrderTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Product ID is required..
        /// </summary>
        public static string ProductIdRequired {
            get {
                return ResourceManager.GetString("ProductIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product type..
        /// </summary>
        public static string ProductTypeInvalid {
            get {
                return ResourceManager.GetString("ProductTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product type is required..
        /// </summary>
        public static string ProductTypeRequired {
            get {
                return ResourceManager.GetString("ProductTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A start date is required..
        /// </summary>
        public static string StartDateRequired {
            get {
                return ResourceManager.GetString("StartDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stop price must be greater than zero..
        /// </summary>
        public static string StopPriceParameterRange {
            get {
                return ResourceManager.GetString("StopPriceParameterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Socket must be connected..
        /// </summary>
        public static string WebSocketMustBeConnected {
            get {
                return ResourceManager.GetString("WebSocketMustBeConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request method is required..
        /// </summary>
        public static string RequestMethodRequired {
            get {
                return ResourceManager.GetString("RequestMethodRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request host is required..
        /// </summary>
        public static string RequestHostRequired {
            get {
                return ResourceManager.GetString("RequestHostRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A request path is required..
        /// </summary>
        public static string RequestPathRequired {
            get {
                return ResourceManager.GetString("RequestPathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid base64 key format..
        /// </summary>
        public static string InvalidBase64KeyFormat {
            get {
                return ResourceManager.GetString("InvalidBase64KeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Ed25519 key length. Expected 64 bytes..
        /// </summary>
        public static string InvalidEd25519KeyLength {
            get {
                return ResourceManager.GetString("InvalidEd25519KeyLength", resourceCulture);
            }
        }
    }
}
