name: Pull Request Build

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened]

env:
  DOTNET_VERSION: '9.0.x'
  SOLUTION_PATH: 'CoinbaseAdvancedTradeClient/CoinbaseAdvancedTradeClient.sln'
  PROJECT_PATH: 'CoinbaseAdvancedTradeClient/CoinbaseAdvancedTradeClient/CoinbaseAdvancedTradeClient.csproj'
  UNIT_TEST_PROJECT_PATH: 'CoinbaseAdvancedTradeClient/CoinbaseAdvancedTradeClient.UnitTests/CoinbaseAdvancedTradeClient.UnitTests.csproj'

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_PATH }}
    
    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration Release --no-restore
    
    - name: Run tests
      run: dotnet test ${{ env.UNIT_TEST_PROJECT_PATH }} --configuration Release --no-build --verbosity normal
    
    - name: Make RC version script executable
      run: chmod +x ./scripts/generate-rc-version.sh
    
    - name: Generate RC version
      id: version
      run: ./scripts/generate-rc-version.sh
    
    - name: Pack NuGet package
      run: dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --no-build --output ./artifacts -p:PackageVersion=${{ steps.version.outputs.version }}
    
    - name: Make tag creation script executable
      run: chmod +x ./scripts/create-tag.sh
    
    - name: Create tag
      run: ./scripts/create-tag.sh "${{ steps.version.outputs.version }}" "${{ github.sha }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Make package publishing script executable
      run: chmod +x ./scripts/publish-package.sh
    
    - name: Publish to GitHub Packages
      run: ./scripts/publish-package.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}